version: "2"
services:
  todoer:
    build: ./app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    command: sh ./start.sh

  postgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_PASSWORD=todoer
      - POSTGRES_USER=todoer
      - POSTGRES_DB=todoer

